#include "analysis.h"
#include "student.h"
#include "marks.h"
#include "attendance.h"
#include "file_manager.h"
#include "utils.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

typedef struct {double overall,avg,highest,lowest,attendance;int subjects,passed,failed;int gradeCounts[7];char category[32];} Perf;
static const char*grade_for(double p){if(p>=90)return "A+";if(p>=80)return "A";if(p>=70)return "B+";if(p>=60)return "B";if(p>=50)return "C";if(p>=40)return "D";return "F";}
static void perf(int sid,Perf*p){memset(p,0,sizeof(*p));p->lowest=101;Mark m[MAX_MARKS];int mn=fm_load_marks(m,MAX_MARKS);double sum=0;for(int i=0;i<mn;i++)if(m[i].student_id==sid){p->subjects++;sum+=m[i].percentage;if(m[i].percentage>p->highest)p->highest=m[i].percentage;if(m[i].percentage<p->lowest)p->lowest=m[i].percentage;if(m[i].percentage>=40)p->passed++;else p->failed++;if(!strcmp(m[i].grade,"A+"))p->gradeCounts[0]++;else if(!strcmp(m[i].grade,"A"))p->gradeCounts[1]++;else if(!strcmp(m[i].grade,"B+"))p->gradeCounts[2]++;else if(!strcmp(m[i].grade,"B"))p->gradeCounts[3]++;else if(!strcmp(m[i].grade,"C"))p->gradeCounts[4]++;else if(!strcmp(m[i].grade,"D"))p->gradeCounts[5]++;else p->gradeCounts[6]++;}if(p->subjects){p->avg=sum/p->subjects;p->overall=p->avg;}else p->lowest=0;Attendance a[MAX_ATTENDANCE];int an=fm_load_attendance(a,MAX_ATTENDANCE);double asum=0;int ac=0;for(int i=0;i<an;i++)if(a[i].student_id==sid){asum+=a[i].percentage;ac++;}p->attendance=ac?asum/ac:0;if(p->overall>=85&&p->attendance>=75&&p->failed==0)strcpy(p->category,"Excellent");else if(p->overall>=75&&p->attendance>=75)strcpy(p->category,"Good");else if(p->overall>=60)strcpy(p->category,"Average");else if(p->overall>=40)strcpy(p->category,"Needs Improvement");else strcpy(p->category,"Critical");}
int analysis_json(int sid,char*out,size_t os){Student s;if(!student_get(sid,&s)){snprintf(out,os,"{\"success\":false,\"message\":\"Student not found\"}");return 0;}Perf p;perf(sid,&p);Mark m[MAX_MARKS];int mn=fm_load_marks(m,MAX_MARKS);Attendance a[MAX_ATTENDANCE];int an=fm_load_attendance(a,MAX_ATTENDANCE);char name[220];json_escape(name,sizeof(name),s.name);size_t pos=0;pos+=snprintf(out+pos,os-pos,"{\"success\":true,\"student\":{\"id\":%d,\"name\":\"%s\",\"roll_no\":\"%s\",\"department\":\"%s\"},\"summary\":{\"overall\":%.2f,\"average\":%.2f,\"highest\":%.2f,\"lowest\":%.2f,\"subjects\":%d,\"passed\":%d,\"failed\":%d,\"attendance\":%.2f,\"category\":\"%s\"},\"subjects\":[",s.student_id,name,s.roll_no,s.department,p.overall,p.avg,p.highest,p.lowest,p.subjects,p.passed,p.failed,p.attendance,p.category);int first=1;for(int i=0;i<mn;i++)if(m[i].student_id==sid){char sub[160],gr[8];json_escape(sub,sizeof(sub),m[i].subject);json_escape(gr,sizeof(gr),m[i].grade);pos+=snprintf(out+pos,os-pos,"%s{\"subject\":\"%s\",\"percentage\":%.2f,\"grade\":\"%s\"}",first?"":",",sub,m[i].percentage,gr);first=0;}pos+=snprintf(out+pos,os-pos,"],\"attendance_records\":[");first=1;for(int i=0;i<an;i++)if(a[i].student_id==sid){char sub[160];json_escape(sub,sizeof(sub),a[i].subject);pos+=snprintf(out+pos,os-pos,"%s{\"subject\":\"%s\",\"percentage\":%.2f}",first?"":",",sub,a[i].percentage);first=0;}pos+=snprintf(out+pos,os-pos,"],\"recommendations\":[");first=1;if(p.attendance<75){pos+=snprintf(out+pos,os-pos,"\"Attendance is below the required level.\"");first=0;}for(int i=0;i<mn;i++)if(m[i].student_id==sid&&m[i].percentage<40){char sub[160];json_escape(sub,sizeof(sub),m[i].subject);pos+=snprintf(out+pos,os-pos,"%s\"Student needs additional support in %s.\"",first?"":",",sub);first=0;}if(p.avg>80){pos+=snprintf(out+pos,os-pos,"%s\"Student is demonstrating strong academic performance.\"",first?"":",");first=0;}if(p.failed>=2){pos+=snprintf(out+pos,os-pos,"%s\"Student requires academic intervention.\"",first?"":",");first=0;}if(first)pos+=snprintf(out+pos,os-pos,"\"Maintain consistent study and attendance habits.\"");pos+=snprintf(out+pos,os-pos,"]}");return 1;}
int dashboard_json(char*out,size_t os){Student s[MAX_STUDENTS];int sn=fm_load_students(s,MAX_STUDENTS);Mark m[MAX_MARKS];int mn=fm_load_marks(m,MAX_MARKS);Attendance a[MAX_ATTENDANCE];int an=fm_load_attendance(a,MAX_ATTENDANCE);double marksum=0,attSum=0;int markcount=0,attcount=0,passedStudents=0,failedStudents=0,atRisk=0;typedef struct{char subject[80];double sum;int count;}Sub;Sub subs[32];int subn=0;int gc[7]={0};double studentAvg[MAX_STUDENTS]={0};for(int i=0;i<sn;i++){int c=0,fail=0;for(int j=0;j<mn;j++)if(m[j].student_id==s[i].student_id){studentAvg[i]+=m[j].percentage;c++;marksum+=m[j].percentage;markcount++;if(m[j].percentage<40)fail++;int k=-1;for(int z=0;z<subn;z++)if(strcmp(subs[z].subject,m[j].subject)==0)k=z;if(k<0){k=subn++;strcpy(subs[k].subject,m[j].subject);subs[k].sum=0;subs[k].count=0;}subs[k].sum+=m[j].percentage;subs[k].count++;if(!strcmp(m[j].grade,"A+"))gc[0]++;else if(!strcmp(m[j].grade,"A"))gc[1]++;else if(!strcmp(m[j].grade,"B+"))gc[2]++;else if(!strcmp(m[j].grade,"B"))gc[3]++;else if(!strcmp(m[j].grade,"C"))gc[4]++;else if(!strcmp(m[j].grade,"D"))gc[5]++;else gc[6]++;}if(c)studentAvg[i]/=c; if(fail>0) failedStudents++; else if(c>0) passedStudents++; int ac=0;double av=0;for(int j=0;j<an;j++)if(a[j].student_id==s[i].student_id){av+=a[j].percentage;ac++;attSum+=a[j].percentage;attcount++;}if(ac)av/=ac;if(fail>=2||av<75)atRisk++;}
size_t p=0;p+=snprintf(out+p,os-p,"{\"success\":true,\"total_students\":%d,\"average_marks\":%.2f,\"average_attendance\":%.2f,\"pass_percentage\":%.2f,\"failed_students\":%d,\"at_risk_students\":%d,\"grade_distribution\":{\"A+\":%d,\"A\":%d,\"B+\":%d,\"B\":%d,\"C\":%d,\"D\":%d,\"F\":%d},\"subject_averages\":[",sn,markcount?marksum/markcount:0,attcount?attSum/attcount:0,sn?((double)passedStudents/sn)*100:0,failedStudents,atRisk,gc[0],gc[1],gc[2],gc[3],gc[4],gc[5],gc[6]);for(int i=0;i<subn;i++)p+=snprintf(out+p,os-p,"%s{\"subject\":\"%s\",\"average\":%.2f}",i?",":"",subs[i].subject,subs[i].count?subs[i].sum/subs[i].count:0);p+=snprintf(out+p,os-p,"],\"students\":[");for(int i=0;i<sn;i++){int ac=0;double av=0;for(int j=0;j<an;j++)if(a[j].student_id==s[i].student_id){av+=a[j].percentage;ac++;}av=ac?av/ac:0;p+=snprintf(out+p,os-p,"%s{\"student_id\":%d,\"name\":\"%s\",\"department\":\"%s\",\"percentage\":%.2f,\"attendance\":%.2f,\"grade\":\"%s\",\"status\":\"%s\"}",i?",":"",s[i].student_id,s[i].name,s[i].department,studentAvg[i],av,grade_for(studentAvg[i]),(studentAvg[i]<40||av<75)?"At Risk":"On Track");}p+=snprintf(out+p,os-p,"]}");return 1;}
