#include "attendance.h"
#include "file_manager.h"
#include "utils.h"
#include <string.h>
#include <stdio.h>
static int load(Attendance*a){return fm_load_attendance(a,MAX_ATTENDANCE);}static void fld(const char*j,const char*k,char*o,size_t n){if(!json_get_string(j,k,o,n))o[0]=0;}void calculate_attendance(Attendance*a){if(a->total_classes<=0)a->total_classes=0;if(a->classes_attended<0)a->classes_attended=0;if(a->classes_attended>a->total_classes)a->classes_attended=a->total_classes;a->classes_absent=a->total_classes-a->classes_attended;a->percentage=a->total_classes?((double)a->classes_attended/a->total_classes)*100.0:0;}
int attendance_add_from_json(const char*j,char*msg,size_t sz){Attendance a;memset(&a,0,sizeof(a));json_get_int(j,"student_id",&a.student_id);json_get_int(j,"total_classes",&a.total_classes);json_get_int(j,"classes_attended",&a.classes_attended);fld(j,"subject",a.subject,sizeof(a.subject));if(a.student_id<=0||!a.subject[0]||a.total_classes<1||a.classes_attended<0||a.classes_attended>a.total_classes){safe_copy(msg,sz,"Invalid attendance values");return 0;}Attendance all[MAX_ATTENDANCE];int n=load(all);a.id=n?all[n-1].id+1:1;calculate_attendance(&a);if(!fm_append_attendance(&a)){safe_copy(msg,sz,"Could not save attendance");return 0;}safe_copy(msg,sz,"Attendance added successfully");return 1;}
int attendance_update_from_json(const char*j,char*msg,size_t sz){int id=0;if(!json_get_int(j,"id",&id)){safe_copy(msg,sz,"Invalid attendance ID");return 0;}Attendance a[MAX_ATTENDANCE];int n=load(a);for(int i=0;i<n;i++)if(a[i].id==id){json_get_int(j,"total_classes",&a[i].total_classes);json_get_int(j,"classes_attended",&a[i].classes_attended);calculate_attendance(&a[i]);if(!fm_save_attendance(a,n)){safe_copy(msg,sz,"Could not update attendance");return 0;}safe_copy(msg,sz,"Attendance updated successfully");return 1;}safe_copy(msg,sz,"Attendance record not found");return 0;}
int attendance_delete(int id,char*msg,size_t sz){Attendance a[MAX_ATTENDANCE];int n=load(a),w=0,found=0;for(int i=0;i<n;i++)if(a[i].id==id)found=1;else a[w++]=a[i];if(!found){safe_copy(msg,sz,"Attendance record not found");return 0;}if(!fm_save_attendance(a,w)){safe_copy(msg,sz,"Could not delete attendance");return 0;}safe_copy(msg,sz,"Attendance deleted successfully");return 1;}
int attendance_json(char*out,size_t os,int sid){Attendance a[MAX_ATTENDANCE];int n=load(a);size_t p=0;out[0]='\0';p+=snprintf(out+p,os-p,"[");int first=1;for(int i=0;i<n;i++)if(a[i].student_id==sid){char sub[160];json_escape(sub,sizeof(sub),a[i].subject);p+=snprintf(out+p,os-p,"%s{\"id\":%d,\"student_id\":%d,\"subject\":\"%s\",\"total_classes\":%d,\"classes_attended\":%d,\"classes_absent\":%d,\"percentage\":%.2f}",first?"":",",a[i].id,a[i].student_id,sub,a[i].total_classes,a[i].classes_attended,a[i].classes_absent,a[i].percentage);first=0;}snprintf(out+p,os-p,"]");return 1;}
