#include "marks.h"
#include "file_manager.h"
#include "utils.h"
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
static int load(Mark*a){return fm_load_marks(a,MAX_MARKS);}static void fld(const char*j,const char*k,char*o,size_t n){if(!json_get_string(j,k,o,n))o[0]=0;}static int dbl(const char*j,const char*k,double*v){char b[64];if(json_get_string(j,k,b,sizeof(b))){*v=strtod(b,NULL);return 1;}int i=0;if(json_get_int(j,k,&i)){*v=i;return 1;}return 0;}
void calculate_mark(Mark*m){m->total_marks=m->internal_marks+m->external_marks+m->practical_marks;if(m->total_marks<0)m->total_marks=0;if(m->max_marks<=0)m->max_marks=100;m->percentage=(m->total_marks/m->max_marks)*100.0;if(m->percentage>=90)strcpy(m->grade,"A+");else if(m->percentage>=80)strcpy(m->grade,"A");else if(m->percentage>=70)strcpy(m->grade,"B+");else if(m->percentage>=60)strcpy(m->grade,"B");else if(m->percentage>=50)strcpy(m->grade,"C");else if(m->percentage>=40)strcpy(m->grade,"D");else strcpy(m->grade,"F");}
int mark_add_from_json(const char*j,char*msg,size_t sz){Mark m;memset(&m,0,sizeof(m));json_get_int(j,"id",&m.id);if(!json_get_int(j,"student_id",&m.student_id)||m.student_id<=0){safe_copy(msg,sz,"Invalid student ID");return 0;}fld(j,"subject",m.subject,sizeof(m.subject));dbl(j,"internal_marks",&m.internal_marks);dbl(j,"external_marks",&m.external_marks);dbl(j,"practical_marks",&m.practical_marks);dbl(j,"max_marks",&m.max_marks);if(!m.subject[0]){safe_copy(msg,sz,"Subject is required");return 0;}if(m.max_marks<=0||m.internal_marks<0||m.external_marks<0||m.practical_marks<0||m.internal_marks+m.external_marks+m.practical_marks>m.max_marks){safe_copy(msg,sz,"Invalid marks values");return 0;}if(m.id==0){Mark all[MAX_MARKS];int n=load(all);m.id=n?all[n-1].id+1:1;}calculate_mark(&m);if(!fm_append_mark(&m)){safe_copy(msg,sz,"Could not save marks");return 0;}safe_copy(msg,sz,"Marks added successfully");return 1;}
int mark_update_from_json(const char*j,char*msg,size_t sz){int id=0;if(!json_get_int(j,"id",&id)){safe_copy(msg,sz,"Invalid mark ID");return 0;}Mark a[MAX_MARKS];int n=load(a);for(int i=0;i<n;i++)if(a[i].id==id){dbl(j,"internal_marks",&a[i].internal_marks);dbl(j,"external_marks",&a[i].external_marks);dbl(j,"practical_marks",&a[i].practical_marks);dbl(j,"max_marks",&a[i].max_marks);calculate_mark(&a[i]);if(!fm_save_marks(a,n)){safe_copy(msg,sz,"Could not update marks");return 0;}safe_copy(msg,sz,"Marks updated successfully");return 1;}safe_copy(msg,sz,"Marks record not found");return 0;}
int mark_delete(int id,char*msg,size_t sz){Mark a[MAX_MARKS];int n=load(a),w=0;int found=0;for(int i=0;i<n;i++)if(a[i].id==id)found=1;else a[w++]=a[i];if(!found){safe_copy(msg,sz,"Marks record not found");return 0;}if(!fm_save_marks(a,w)){safe_copy(msg,sz,"Could not delete marks");return 0;}safe_copy(msg,sz,"Marks deleted successfully");return 1;}
int marks_json(char*out,size_t os,int sid){Mark a[MAX_MARKS];int n=load(a);size_t p=0;out[0]='\0';p+=snprintf(out+p,os-p,"[");int first=1;for(int i=0;i<n;i++)if(a[i].student_id==sid){char sub[160],gr[8];json_escape(sub,sizeof(sub),a[i].subject);json_escape(gr,sizeof(gr),a[i].grade);p+=snprintf(out+p,os-p,"%s{\"id\":%d,\"student_id\":%d,\"subject\":\"%s\",\"internal_marks\":%.2f,\"external_marks\":%.2f,\"practical_marks\":%.2f,\"total_marks\":%.2f,\"max_marks\":%.2f,\"percentage\":%.2f,\"grade\":\"%s\"}",first?"":",",a[i].id,a[i].student_id,sub,a[i].internal_marks,a[i].external_marks,a[i].practical_marks,a[i].total_marks,a[i].max_marks,a[i].percentage,gr);first=0;}snprintf(out+p,os-p,"]");return 1;}
