#include "reports.h"
#include "student.h"
#include "marks.h"
#include "attendance.h"
#include "analysis.h"
#include "file_manager.h"
#include "utils.h"
#include <stdio.h>
#include <string.h>
#include <time.h>
static void safe_name(char*out,size_t n,const char*src){size_t p=0;for(size_t i=0;src&&src[i]&&p+1<n;i++)if((src[i]>='a'&&src[i]<='z')||(src[i]>='A'&&src[i]<='Z')||(src[i]>='0'&&src[i]<='9')||src[i]=='_'||src[i]=='-')out[p++]=src[i];out[p]='\0';}
int report_student(int sid,char*fn,size_t fs){Student s;if(!student_get(sid,&s))return 0;char n[80];safe_name(n,sizeof(n),s.name);snprintf(fn,fs,"reports/student_%d_%s.txt",sid,n);FILE*f=fopen(fn,"w");if(!f)return 0;Mark m[MAX_MARKS];int mn=fm_load_marks(m,MAX_MARKS);Attendance a[MAX_ATTENDANCE];int an=fm_load_attendance(a,MAX_ATTENDANCE);fprintf(f,"STUDENT PERFORMANCE REPORT\n==========================\nStudent ID: %d\nRoll No: %s\nName: %s\nDepartment: %s\nSemester: %d Section: %s\n\nMARKS\n-----\n",s.student_id,s.roll_no,s.name,s.department,s.semester,s.section);double sum=0;int c=0;for(int i=0;i<mn;i++)if(m[i].student_id==sid){fprintf(f,"%-22s %7.2f%% %3s\n",m[i].subject,m[i].percentage,m[i].grade);sum+=m[i].percentage;c++;}fprintf(f,"Overall Percentage: %.2f%%\n\nATTENDANCE\n----------\n",c?sum/c:0);double asum=0;int ac=0;for(int i=0;i<an;i++)if(a[i].student_id==sid){fprintf(f,"%-22s %5d/%-5d %7.2f%%\n",a[i].subject,a[i].classes_attended,a[i].total_classes,a[i].percentage);asum+=a[i].percentage;ac++;}double av=ac?asum/ac:0; double overall=c?sum/c:0; const char *category=(overall>=85&&av>=75)?"Excellent":(overall>=75?"Good":(overall>=60?"Average":(overall>=40?"Needs Improvement":"Critical"))); fprintf(f,"Average Attendance: %.2f%%\n\nANALYSIS\n--------\nOverall Percentage: %.2f%%\nPerformance Category: %s\nRecommendations:\n",av,overall,category);if(av<75)fprintf(f,"- Attendance is below the required level.\n");for(int i=0;i<mn;i++)if(m[i].student_id==sid&&m[i].percentage<40)fprintf(f,"- Student needs additional support in %s.\n",m[i].subject);if((c?(sum/c):0)>80)fprintf(f,"- Student is demonstrating strong academic performance.\n");fprintf(f,"\nGenerated locally by the C backend.\n");fclose(f);return 1;}
int report_class(char*fn,size_t fs){time_t t=time(NULL);snprintf(fn,fs,"reports/class_%ld.txt",(long)t);FILE*f=fopen(fn,"w");if(!f)return 0;Student s[MAX_STUDENTS];int n=fm_load_students(s,MAX_STUDENTS);Mark m[MAX_MARKS];int mn=fm_load_marks(m,MAX_MARKS);Attendance a[MAX_ATTENDANCE];int an=fm_load_attendance(a,MAX_ATTENDANCE);double ms=0,as=0;int mc=0,ac=0,passed=0;for(int i=0;i<mn;i++){ms+=m[i].percentage;mc++;if(m[i].percentage>=40)passed++;}for(int i=0;i<an;i++){as+=a[i].percentage;ac++;}fprintf(f,"CLASS PERFORMANCE REPORT\n========================\nTotal Students: %d\nAverage Marks: %.2f%%\nAverage Attendance: %.2f%%\nPass Percentage (record-level): %.2f%%\n\nStudents:\n",n,mc?ms/mc:0,ac?as/ac:0,mc?100.0*passed/mc:0);for(int i=0;i<n;i++)fprintf(f,"%d | %-24s | %s\n",s[i].student_id,s[i].name,s[i].department);fclose(f);return 1;}
int report_subject(const char*subject,char*fn,size_t fs){char sn[100];safe_name(sn,sizeof(sn),subject);time_t t=time(NULL);snprintf(fn,fs,"reports/subject_%s_%ld.txt",sn,(long)t);FILE*f=fopen(fn,"w");if(!f)return 0;Mark m[MAX_MARKS];int n=fm_load_marks(m,MAX_MARKS);double sum=0,hi=0,lo=101;int c=0,pass=0;for(int i=0;i<n;i++)if(strcmp(m[i].subject,subject)==0){sum+=m[i].percentage;if(m[i].percentage>hi)hi=m[i].percentage;if(m[i].percentage<lo)lo=m[i].percentage;c++;if(m[i].percentage>=40)pass++;}fprintf(f,"SUBJECT REPORT\n==============\nSubject: %s\nRecords: %d\nAverage: %.2f%%\nHighest: %.2f%%\nLowest: %.2f%%\nPass Percentage: %.2f%%\nFail Percentage: %.2f%%\n",subject,c,c?sum/c:0,c?hi:0,c?lo:0,c?100.0*pass/c:0,c?100.0*(c-pass)/c:0);fclose(f);return 1;}
