#include "router.h"
#include "student.h"
#include "marks.h"
#include "attendance.h"
#include "analysis.h"
#include "reports.h"
#include "utils.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

static void send_raw(socket_t c,const char*status,const char*type,const char*body){char h[512];size_t n=strlen(body);snprintf(h,sizeof(h),"HTTP/1.1 %s\r\nContent-Type: %s\r\nContent-Length: %zu\r\nAccess-Control-Allow-Origin: *\r\nCache-Control: no-store\r\nConnection: close\r\n\r\n",status,type,n);send(c,h,(int)strlen(h),0);send(c,body,(int)n,0);}
static void json(socket_t c,int ok,const char*body){send_raw(c,ok?"200 OK":"400 Bad Request","application/json; charset=utf-8",body);}
static void serve_file(socket_t c,const char*path){char clean[260];if(strcmp(path,"/")==0||strcmp(path,"/index.html")==0)strcpy(clean,"frontend/dashboard.html");else if(strcmp(path,"/dashboard")==0)strcpy(clean,"frontend/dashboard.html");else if(strcmp(path,"/students")==0)strcpy(clean,"frontend/students.html");else if(strcmp(path,"/student-profile")==0)strcpy(clean,"frontend/student-profile.html");else if(strcmp(path,"/marks")==0)strcpy(clean,"frontend/marks.html");else if(strcmp(path,"/attendance")==0)strcpy(clean,"frontend/attendance.html");else if(strcmp(path,"/analysis")==0)strcpy(clean,"frontend/analysis.html");else if(strcmp(path,"/reports")==0)strcpy(clean,"frontend/reports.html");else if(strncmp(path,"/css/",5)==0||strncmp(path,"/js/",4)==0){if(strlen(path)+9>=sizeof(clean)){send_raw(c,"414 URI Too Long","text/plain","URI too long");return;} snprintf(clean,sizeof(clean),"frontend%s",path);}else {send_raw(c,"404 Not Found","text/plain","Not Found");return;}FILE*f=fopen(clean,"rb");if(!f){send_raw(c,"404 Not Found","text/plain","File not found");return;}fseek(f,0,SEEK_END);long sz=ftell(f);fseek(f,0,SEEK_SET);if(sz<0||sz>1024*1024){fclose(f);send_raw(c,"500 Internal Server Error","text/plain","File error");return;}char*data=(char*)malloc((size_t)sz+1);if(!data){fclose(f);send_raw(c,"500 Internal Server Error","text/plain","Memory error");return;}fread(data,1,(size_t)sz,f);fclose(f);data[sz]='\0';const char*type=strstr(clean,".html")?"text/html; charset=utf-8":strstr(clean,".css")?"text/css; charset=utf-8":strstr(clean,".js")?"application/javascript; charset=utf-8":"application/octet-stream";send_raw(c,"200 OK",type,data);free(data);}
static const char* query_param(const char*path,const char*key,char*out,size_t os){const char*q=strchr(path,'?');if(!q)return NULL;q++;size_t kl=strlen(key);while(q&&*q){const char*eq=strchr(q,'=');if(!eq)break;const char*amp=strchr(eq+1,'&');size_t kn=(size_t)(eq-q);if(kn==kl&&strncmp(q,key,kl)==0){size_t n=amp?(size_t)(amp-(eq+1)):strlen(eq+1);if(n>=os)n=os-1;memcpy(out,eq+1,n);out[n]='\0';url_decode(out,os,out);return out;}q=amp?amp+1:NULL;}return NULL;}
static int path_id(const char*path,const char*prefix){const char*p=path+strlen(prefix);return atoi(p);}
static void report_download(socket_t c,const char*fn){FILE*f=fopen(fn,"rb");if(!f){send_raw(c,"404 Not Found","text/plain","Report not found");return;}fseek(f,0,SEEK_END);long sz=ftell(f);fseek(f,0,SEEK_SET);char*data=malloc((size_t)sz+1);if(!data){fclose(f);send_raw(c,"500 Internal Server Error","text/plain","Memory error");return;}fread(data,1,(size_t)sz,f);fclose(f);data[sz]='\0';char h[512];snprintf(h,sizeof(h),"HTTP/1.1 200 OK\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Disposition: attachment; filename=\"%s\"\r\nContent-Length: %ld\r\nConnection: close\r\n\r\n",strrchr(fn,'/')?strrchr(fn,'/')+1:fn,sz);send(c,h,(int)strlen(h),0);send(c,data,(int)sz,0);free(data);}

void route_request(socket_t c,const char*method,const char*rawpath,const char*headers,const char*body){
 (void)headers;char path[2048];safe_copy(path,sizeof(path),rawpath);char *q=strchr(path,'?');if(q)*q='\0';
 if((!strcmp(method,"GET")||!strcmp(method,"HEAD"))&&path[0]!='/'){send_raw(c,"400 Bad Request","text/plain","Bad request");return;}
 if(!strncmp(path,"/api/",5)){
   if(!strcmp(method,"GET")&&!strcmp(path,"/api/dashboard")){char r[65536];dashboard_json(r,sizeof(r));json(c,1,r);return;}
   if(!strcmp(method,"GET")&&!strcmp(path,"/api/students")){char r[65536],qv[120]={0};query_param(rawpath,"q",qv,sizeof(qv));student_list_json(r,sizeof(r),qv);json(c,1,r);return;}
   if(!strcmp(method,"GET")&&!strncmp(path,"/api/students/",15)){int id=path_id(path,"/api/students/");Student s;if(!student_get(id,&s)){json(c,0,"{\"success\":false,\"message\":\"Student not found\"}");return;}char r[4096],name[220],roll[80],email[140],phone[40],gender[40],dob[40],dep[120],course[80],section[20];json_escape(name,sizeof(name),s.name);json_escape(roll,sizeof(roll),s.roll_no);json_escape(email,sizeof(email),s.email);json_escape(phone,sizeof(phone),s.phone);json_escape(gender,sizeof(gender),s.gender);json_escape(dob,sizeof(dob),s.dob);json_escape(dep,sizeof(dep),s.department);json_escape(course,sizeof(course),s.course);json_escape(section,sizeof(section),s.section);snprintf(r,sizeof(r),"{\"success\":true,\"student\":{\"student_id\":%d,\"roll_no\":\"%s\",\"name\":\"%s\",\"email\":\"%s\",\"phone\":\"%s\",\"gender\":\"%s\",\"dob\":\"%s\",\"department\":\"%s\",\"course\":\"%s\",\"semester\":%d,\"section\":\"%s\",\"admission_year\":%d}}",s.student_id,roll,name,email,phone,gender,dob,dep,course,s.semester,section,s.admission_year);json(c,1,r);return;}
   if(!strcmp(method,"POST")&&!strcmp(path,"/api/students/add")){char msg[160];int ok=student_add_from_json(body,msg,sizeof(msg));char e[220];json_escape(e,sizeof(e),msg);char r[300];snprintf(r,sizeof(r),"{\"success\":%s,\"message\":\"%s\"}",ok?"true":"false",e);json(c,ok,r);return;}
   if(!strcmp(method,"POST")&&!strcmp(path,"/api/students/update")){char msg[160];int ok=student_update_from_json(body,msg,sizeof(msg));char e[220];json_escape(e,sizeof(e),msg);char r[300];snprintf(r,sizeof(r),"{\"success\":%s,\"message\":\"%s\"}",ok?"true":"false",e);json(c,ok,r);return;}
   if(!strcmp(method,"POST")&&!strcmp(path,"/api/students/delete")){int id=0;json_get_int(body,"student_id",&id);char msg[160];int ok=student_delete(id,msg,sizeof(msg));char e[220];json_escape(e,sizeof(e),msg);char r[300];snprintf(r,sizeof(r),"{\"success\":%s,\"message\":\"%s\"}",ok?"true":"false",e);json(c,ok,r);return;}
   if(!strcmp(method,"GET")&&!strcmp(path,"/api/marks")){char sid[32]={0};query_param(rawpath,"student_id",sid,sizeof(sid));char r[30000];marks_json(r,sizeof(r),atoi(sid));json(c,1,r);return;}
   if(!strcmp(method,"POST")&&!strcmp(path,"/api/marks/add")){char msg[160];int ok=mark_add_from_json(body,msg,sizeof(msg));char e[220];json_escape(e,sizeof(e),msg);char r[300];snprintf(r,sizeof(r),"{\"success\":%s,\"message\":\"%s\"}",ok?"true":"false",e);json(c,ok,r);return;}
   if(!strcmp(method,"POST")&&!strcmp(path,"/api/marks/update")){char msg[160];int ok=mark_update_from_json(body,msg,sizeof(msg));char e[220];json_escape(e,sizeof(e),msg);char r[300];snprintf(r,sizeof(r),"{\"success\":%s,\"message\":\"%s\"}",ok?"true":"false",e);json(c,ok,r);return;}
   if(!strcmp(method,"POST")&&!strcmp(path,"/api/marks/delete")){int id=0;json_get_int(body,"id",&id);char msg[160];int ok=mark_delete(id,msg,sizeof(msg));char e[220];json_escape(e,sizeof(e),msg);char r[300];snprintf(r,sizeof(r),"{\"success\":%s,\"message\":\"%s\"}",ok?"true":"false",e);json(c,ok,r);return;}
   if(!strcmp(method,"GET")&&!strcmp(path,"/api/attendance")){char sid[32]={0};query_param(rawpath,"student_id",sid,sizeof(sid));char r[30000];attendance_json(r,sizeof(r),atoi(sid));json(c,1,r);return;}
   if(!strcmp(method,"POST")&&!strcmp(path,"/api/attendance/add")){char msg[160];int ok=attendance_add_from_json(body,msg,sizeof(msg));char e[220];json_escape(e,sizeof(e),msg);char r[300];snprintf(r,sizeof(r),"{\"success\":%s,\"message\":\"%s\"}",ok?"true":"false",e);json(c,ok,r);return;}
   if(!strcmp(method,"POST")&&!strcmp(path,"/api/attendance/update")){char msg[160];int ok=attendance_update_from_json(body,msg,sizeof(msg));char e[220];json_escape(e,sizeof(e),msg);char r[300];snprintf(r,sizeof(r),"{\"success\":%s,\"message\":\"%s\"}",ok?"true":"false",e);json(c,ok,r);return;}
   if(!strcmp(method,"POST")&&!strcmp(path,"/api/attendance/delete")){int id=0;json_get_int(body,"id",&id);char msg[160];int ok=attendance_delete(id,msg,sizeof(msg));char e[220];json_escape(e,sizeof(e),msg);char r[300];snprintf(r,sizeof(r),"{\"success\":%s,\"message\":\"%s\"}",ok?"true":"false",e);json(c,ok,r);return;}
   if(!strcmp(method,"GET")&&!strncmp(path,"/api/analysis/",14)){int id=path_id(path,"/api/analysis/");char r[50000];analysis_json(id,r,sizeof(r));json(c,1,r);return;}
   if(!strcmp(method,"GET")&&!strncmp(path,"/api/reports/student/",21)){int id=path_id(path,"/api/reports/student/");char fn[260];if(!report_student(id,fn,sizeof(fn))){send_raw(c,"404 Not Found","text/plain","Report unavailable");return;}report_download(c,fn);return;}
   if(!strcmp(method,"GET")&&!strcmp(path,"/api/reports/class")){char fn[260];if(!report_class(fn,sizeof(fn))){send_raw(c,"500 Internal Server Error","text/plain","Report generation failed");return;}report_download(c,fn);return;}
   if(!strcmp(method,"GET")&&!strcmp(path,"/api/reports/subject")){char sv[100]={0};query_param(rawpath,"subject",sv,sizeof(sv));if(!sv[0]){send_raw(c,"400 Bad Request","text/plain","Subject required");return;}char fn[260];if(!report_subject(sv,fn,sizeof(fn))){send_raw(c,"500 Internal Server Error","text/plain","Report generation failed");return;}report_download(c,fn);return;}
   json(c,0,"{\"success\":false,\"message\":\"API route not found\"}");return;
 }
 serve_file(c,path);
}
