#include "student.h"
#include "file_manager.h"
#include "utils.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
static int load(Student*a){return fm_load_students(a,MAX_STUDENTS);}int student_exists_id(int id){Student a[MAX_STUDENTS];int n=load(a);for(int i=0;i<n;i++)if(a[i].student_id==id)return 1;return 0;}int student_exists_roll(const char*r,int ex){Student a[MAX_STUDENTS];int n=load(a);for(int i=0;i<n;i++)if(a[i].student_id!=ex&&strcmp(a[i].roll_no,r)==0)return 1;return 0;}int student_get(int id,Student*out){Student a[MAX_STUDENTS];int n=load(a);for(int i=0;i<n;i++)if(a[i].student_id==id){*out=a[i];return 1;}return 0;}
static void field(const char*j,const char*k,char*o,size_t n){if(!json_get_string(j,k,o,n))o[0]=0;}
int student_add_from_json(const char*j,char*msg,size_t ms){Student s;memset(&s,0,sizeof(s));int id=0;if(!json_get_int(j,"student_id",&id)||id<=0){safe_copy(msg,ms,"Invalid Student ID");return 0;}s.student_id=id;field(j,"roll_no",s.roll_no,sizeof(s.roll_no));field(j,"name",s.name,sizeof(s.name));field(j,"email",s.email,sizeof(s.email));field(j,"phone",s.phone,sizeof(s.phone));field(j,"gender",s.gender,sizeof(s.gender));field(j,"dob",s.dob,sizeof(s.dob));field(j,"department",s.department,sizeof(s.department));field(j,"course",s.course,sizeof(s.course));field(j,"section",s.section,sizeof(s.section));json_get_int(j,"semester",&s.semester);json_get_int(j,"admission_year",&s.admission_year);if(!s.name[0]||!s.roll_no[0]||!s.department[0]||s.semester<1||s.semester>12){safe_copy(msg,ms,"Missing or invalid student fields");return 0;}if(student_exists_id(s.student_id)){safe_copy(msg,ms,"Student ID already exists");return 0;}if(student_exists_roll(s.roll_no,0)){safe_copy(msg,ms,"Roll number already exists");return 0;}if(!fm_append_student(&s)){safe_copy(msg,ms,"Could not save student");return 0;}safe_copy(msg,ms,"Student added successfully");return 1;}
int student_update_from_json(const char*j,char*msg,size_t ms){int id=0;if(!json_get_int(j,"student_id",&id)){safe_copy(msg,ms,"Invalid Student ID");return 0;}Student s;if(!student_get(id,&s)){safe_copy(msg,ms,"Student not found");return 0;}field(j,"roll_no",s.roll_no,sizeof(s.roll_no));field(j,"name",s.name,sizeof(s.name));field(j,"email",s.email,sizeof(s.email));field(j,"phone",s.phone,sizeof(s.phone));field(j,"gender",s.gender,sizeof(s.gender));field(j,"dob",s.dob,sizeof(s.dob));field(j,"department",s.department,sizeof(s.department));field(j,"course",s.course,sizeof(s.course));field(j,"section",s.section,sizeof(s.section));json_get_int(j,"semester",&s.semester);json_get_int(j,"admission_year",&s.admission_year);if(student_exists_roll(s.roll_no,id)){safe_copy(msg,ms,"Roll number already exists");return 0;}Student a[MAX_STUDENTS];int n=load(a);for(int i=0;i<n;i++)if(a[i].student_id==id){a[i]=s;break;}if(!fm_save_students(a,n)){safe_copy(msg,ms,"Could not update student");return 0;}safe_copy(msg,ms,"Student updated successfully");return 1;}
int student_delete(int id,char*msg,size_t ms){Student a[MAX_STUDENTS];int n=load(a),w=0,found=0;for(int i=0;i<n;i++)if(a[i].student_id==id)found=1;else a[w++]=a[i];if(!found){safe_copy(msg,ms,"Student not found");return 0;}if(!fm_save_students(a,w)){safe_copy(msg,ms,"Could not delete student");return 0;}safe_copy(msg,ms,"Student deleted successfully");return 1;}
int student_list_json(char*out,size_t os,const char*q){Student a[MAX_STUDENTS];int n=load(a);size_t p=0;p+=snprintf(out+p,os-p,"[");for(int i=0;i<n;i++){char name[220],dep[100],roll[60];json_escape(name,sizeof(name),a[i].name);json_escape(dep,sizeof(dep),a[i].department);json_escape(roll,sizeof(roll),a[i].roll_no);int ok=!q||!*q||strstr(a[i].name,q)||strstr(a[i].roll_no,q)||strstr(a[i].department,q);if(!ok)continue;if(p>1)p+=snprintf(out+p,os-p,",");p+=snprintf(out+p,os-p,"{\"student_id\":%d,\"roll_no\":\"%s\",\"name\":\"%s\",\"department\":\"%s\",\"semester\":%d,\"section\":\"%s\",\"email\":\"%s\"}",a[i].student_id,roll,name,dep,a[i].semester,a[i].section,a[i].email);}snprintf(out+p,os-p,"]");return 1;}
